language: java
jobs:
  include:
    - name: hnclient-v2
      env: DIR=hnclient-v2
    - name: mock-hnsecure
      env: DIR=mock-hnsecure
    - name: mock-point-of-service
      env: DIR=mock-point-of-service
script: cd $DIR && mvn test -B
